// ============================================
// Admin Panel — Mock Data
// Dữ liệu mẫu cho giao diện Admin.
// Khi kết nối API thật, thay bằng fetch().
// ============================================

import type {
    Account,
    Character,
    ItemTemplate,
    MobConfig,
    GameMap,
    DashboardStats,
} from './types';

export const mockStats: DashboardStats = {
    totalAccounts: 1247,
    totalCharacters: 2891,
    totalItems: 156,
    totalMaps: 8,
    totalMobs: 47,
    onlineNow: 89,
};

export const mockAccounts: Account[] = [
    {
        id: 1,
        username: 'player_alpha',
        email: 'alpha@example.com',
        status: 'active',
        last_login_at: '2026-03-05T10:30:00Z',
        last_login_ip: '192.168.1.100',
        created_at: '2026-01-15T08:00:00Z',
    },
    {
        id: 2,
        username: 'dragon_master',
        email: 'dragon@example.com',
        status: 'active',
        last_login_at: '2026-03-05T09:15:00Z',
        last_login_ip: '10.0.0.55',
        created_at: '2026-01-20T12:00:00Z',
    },
    {
        id: 3,
        username: 'hacker_suspect',
        email: 'hack@example.com',
        status: 'banned',
        last_login_at: '2026-02-28T16:00:00Z',
        last_login_ip: '203.0.113.42',
        created_at: '2026-02-01T06:00:00Z',
    },
    {
        id: 4,
        username: 'iron_knight',
        email: 'knight@example.com',
        status: 'active',
        last_login_at: '2026-03-04T22:45:00Z',
        last_login_ip: '172.16.0.12',
        created_at: '2026-01-22T14:30:00Z',
    },
    {
        id: 5,
        username: 'toxic_player',
        email: 'toxic@example.com',
        status: 'suspended',
        last_login_at: '2026-03-01T11:00:00Z',
        last_login_ip: '192.168.2.200',
        created_at: '2026-02-10T09:00:00Z',
    },
];

export const mockCharacters: Character[] = [
    {
        id: 1,
        account_id: 1,
        name: 'Lina',
        level: 25,
        experience: 48500,
        hp: 450,
        max_hp: 450,
        mp: 180,
        max_mp: 180,
        attack: 85,
        defense: 42,
        accuracy: 120,
        evasion: 28,
        speed: 35,
        crit_chance: 0.12,
        magic_resistance: 15,
        effect_resistance: 10,
        stat_points: 5,
        current_map_id: 'area_ruined_city',
        current_node_id: 'n4',
        created_at: '2026-01-15T08:05:00Z',
    },
    {
        id: 2,
        account_id: 1,
        name: 'Shadow',
        level: 12,
        experience: 15200,
        hp: 280,
        max_hp: 280,
        mp: 120,
        max_mp: 120,
        attack: 45,
        defense: 22,
        accuracy: 105,
        evasion: 35,
        speed: 48,
        crit_chance: 0.18,
        magic_resistance: 8,
        effect_resistance: 5,
        stat_points: 0,
        current_map_id: null,
        current_node_id: null,
        created_at: '2026-02-01T10:00:00Z',
    },
    {
        id: 3,
        account_id: 2,
        name: 'DragonSlayer',
        level: 42,
        experience: 128000,
        hp: 820,
        max_hp: 820,
        mp: 340,
        max_mp: 340,
        attack: 165,
        defense: 88,
        accuracy: 145,
        evasion: 45,
        speed: 42,
        crit_chance: 0.15,
        magic_resistance: 30,
        effect_resistance: 22,
        stat_points: 10,
        current_map_id: 'area_glow_forest',
        current_node_id: 'n7',
        created_at: '2026-01-20T12:10:00Z',
    },
    {
        id: 4,
        account_id: 4,
        name: 'IronGuard',
        level: 18,
        experience: 28900,
        hp: 520,
        max_hp: 520,
        mp: 90,
        max_mp: 90,
        attack: 55,
        defense: 95,
        accuracy: 100,
        evasion: 12,
        speed: 15,
        crit_chance: 0.05,
        magic_resistance: 20,
        effect_resistance: 18,
        stat_points: 3,
        current_map_id: 'area_ruined_city',
        current_node_id: 'n2',
        created_at: '2026-01-22T14:35:00Z',
    },
];

export const mockItemTemplates: ItemTemplate[] = [
    {
        _id: 'weapon_iron_sword_001',
        name: 'Kiếm Thiết Tinh',
        description: 'Thanh kiếm rèn từ mảnh Thiết Tinh nguyên chất.',
        category: 'weapon',
        slotType: 'weapon',
        mainStat: { type: 'attack', baseValue: 15, growthPerLevel: 3 },
        subStatPool: [
            { type: 'speed', minValue: 1, maxValue: 8 },
            { type: 'critChance', minValue: 0.01, maxValue: 0.05 },
            { type: 'hp', minValue: 10, maxValue: 50 },
        ],
        possibleRarities: [1, 2, 3, 4, 5],
        maxSockets: 2,
        setId: 'iron_crystal_set',
        requirements: { minLevel: 1 },
        dropInfo: { mapIds: ['area_ruined_city', 'area_glow_forest'], baseDropRate: 0.08 },
    },
    {
        _id: 'armor_iron_chest_001',
        name: 'Giáp Thiết Tinh',
        description: 'Giáp ngực rèn từ Thiết Tinh, cứng như đá.',
        category: 'armor',
        slotType: 'armor',
        mainStat: { type: 'defense', baseValue: 12, growthPerLevel: 2 },
        subStatPool: [
            { type: 'hp', minValue: 20, maxValue: 80 },
            { type: 'evasion', minValue: 1, maxValue: 5 },
        ],
        possibleRarities: [1, 2, 3, 4],
        maxSockets: 1,
        setId: 'iron_crystal_set',
        requirements: { minLevel: 5 },
        dropInfo: { mapIds: ['area_ruined_city'], baseDropRate: 0.06 },
    },
    {
        _id: 'accessory_iron_ring_001',
        name: 'Nhẫn Thiết Tinh',
        description: 'Nhẫn khắc ấn của thợ rèn cổ đại.',
        category: 'accessory',
        slotType: 'accessory',
        mainStat: { type: 'accuracy', baseValue: 8, growthPerLevel: 2 },
        subStatPool: [
            { type: 'critChance', minValue: 0.02, maxValue: 0.08 },
            { type: 'speed', minValue: 2, maxValue: 6 },
        ],
        possibleRarities: [2, 3, 4, 5],
        maxSockets: 1,
        setId: 'iron_crystal_set',
        requirements: { minLevel: 10 },
        dropInfo: { mapIds: ['area_glow_forest'], baseDropRate: 0.04 },
    },
    {
        _id: 'consumable_hp_potion_s',
        name: 'Bình Máu Nhỏ',
        description: 'Hồi phục 50 HP ngay lập tức.',
        category: 'consumable',
        slotType: 'consumable',
        mainStat: { type: 'hp', baseValue: 50, growthPerLevel: 0 },
        subStatPool: [],
        possibleRarities: [1],
        maxSockets: 0,
        setId: null,
        requirements: { minLevel: 1 },
        dropInfo: { mapIds: ['area_ruined_city', 'area_glow_forest'], baseDropRate: 0.15 },
    },
    {
        _id: 'material_iron_shard',
        name: 'Mảnh Thiết Tinh',
        description: 'Mảnh khoáng chất dùng để nâng cấp trang bị.',
        category: 'material',
        slotType: 'material',
        mainStat: { type: 'attack', baseValue: 0, growthPerLevel: 0 },
        subStatPool: [],
        possibleRarities: [1, 2, 3],
        maxSockets: 0,
        setId: null,
        requirements: { minLevel: 1 },
        dropInfo: { mapIds: ['area_ruined_city'], baseDropRate: 0.30 },
    },
    {
        _id: 'gem_fire_ruby_001',
        name: 'Hồng Ngọc Lửa',
        description: 'Ngọc khảm tăng sức tấn công.',
        category: 'gem',
        slotType: 'gem',
        mainStat: { type: 'attack', baseValue: 10, growthPerLevel: 2 },
        subStatPool: [
            { type: 'critChance', minValue: 0.01, maxValue: 0.03 },
        ],
        possibleRarities: [3, 4, 5, 6],
        maxSockets: 0,
        setId: null,
        requirements: { minLevel: 15 },
        dropInfo: { mapIds: ['area_glow_forest'], baseDropRate: 0.02 },
    },
];

export const mockMobs: MobConfig[] = [
    {
        _id: 'mob_mutant_rat',
        name: 'Chuột Đột Biến',
        description: 'Loài chuột bị nhiễm năng lượng Thiết Tinh, trở nên hung hãn.',
        baseStats: { hp: 50, attack: 8, defense: 2, speed: 12, critChance: 0.02 },
        scalingPerLevel: { hp: 15, attack: 3, defense: 1, speed: 1 },
        rewards: { baseExp: 15, baseGold: 10, expScaling: 5, goldScaling: 3 },
        dropTable: [
            { itemTemplateId: 'material_iron_shard', dropRate: 0.30, minQty: 1, maxQty: 3 },
            { itemTemplateId: 'weapon_iron_sword_001', dropRate: 0.05, minQty: 1, maxQty: 1 },
            { itemTemplateId: 'consumable_hp_potion_s', dropRate: 0.15, minQty: 1, maxQty: 2 },
        ],
        spawnMaps: ['area_ruined_city'],
        isBoss: false,
    },
    {
        _id: 'mob_iron_golem',
        name: 'Golem Sắt',
        description: 'Cỗ máy chiến đấu cổ đại, thân thể bằng Thiết Tinh đặc.',
        baseStats: { hp: 200, attack: 25, defense: 30, speed: 4, critChance: 0.01 },
        scalingPerLevel: { hp: 40, attack: 8, defense: 6, speed: 0 },
        rewards: { baseExp: 60, baseGold: 35, expScaling: 15, goldScaling: 8 },
        dropTable: [
            { itemTemplateId: 'material_iron_shard', dropRate: 0.50, minQty: 2, maxQty: 5 },
            { itemTemplateId: 'armor_iron_chest_001', dropRate: 0.08, minQty: 1, maxQty: 1 },
        ],
        spawnMaps: ['area_ruined_city'],
        isBoss: false,
    },
    {
        _id: 'boss_crystal_guardian',
        name: 'Thủ Hộ Tinh Thể',
        description: 'Boss canh giữ lõi Thiết Tinh cổ đại.',
        baseStats: { hp: 800, attack: 45, defense: 40, speed: 10, critChance: 0.08 },
        scalingPerLevel: { hp: 100, attack: 12, defense: 10, speed: 2 },
        rewards: { baseExp: 250, baseGold: 150, expScaling: 50, goldScaling: 30 },
        dropTable: [
            { itemTemplateId: 'gem_fire_ruby_001', dropRate: 0.20, minQty: 1, maxQty: 1 },
            { itemTemplateId: 'weapon_iron_sword_001', dropRate: 0.30, minQty: 1, maxQty: 1 },
            { itemTemplateId: 'accessory_iron_ring_001', dropRate: 0.15, minQty: 1, maxQty: 1 },
        ],
        spawnMaps: ['area_ruined_city'],
        isBoss: true,
    },
];

export const mockMaps: GameMap[] = [
    {
        id: 'area_ruined_city',
        name: 'Phế Tích Thiết Tinh',
        description: 'Tàn tích của thành phố cổ đại bị phá hủy bởi năng lượng Thiết Tinh.',
        level: 1,
        nodes: [
            { id: 'n1', label: 'Cổng Vào', type: 'empty', x: 80, y: 250, connections: ['n2', 'n3'] },
            { id: 'n2', label: 'Ngã Ba Rêu', type: 'mob', x: 220, y: 150, connections: ['n1', 'n4'] },
            { id: 'n3', label: 'Lối Mòn', type: 'mob', x: 220, y: 350, connections: ['n1', 'n5'] },
            { id: 'n4', label: 'Hành Lang Tối', type: 'mob', x: 380, y: 100, connections: ['n2', 'n6'] },
            { id: 'n5', label: 'Kho Hoang', type: 'treasure', x: 380, y: 350, connections: ['n3', 'n6'] },
            { id: 'n6', label: 'Lõi Phế Tích', type: 'boss', x: 540, y: 250, connections: ['n4', 'n5'] },
        ],
    },
    {
        id: 'area_glow_forest',
        name: 'Rừng Phát Quang',
        description: 'Khu rừng nhiễm phóng xạ Thiết Tinh, cây cối phát sáng.',
        level: 5,
        nodes: [
            { id: 'n1', label: 'Bìa Rừng', type: 'empty', x: 80, y: 200, connections: ['n2'] },
            { id: 'n2', label: 'Bụi Rậm', type: 'mob', x: 200, y: 120, connections: ['n1', 'n3', 'n4'] },
            { id: 'n3', label: 'Suối Sáng', type: 'event', x: 200, y: 300, connections: ['n2', 'n5'] },
            { id: 'n4', label: 'Đỉnh Đồi', type: 'mob', x: 350, y: 80, connections: ['n2', 'n6'] },
            { id: 'n5', label: 'Hang Nấm', type: 'treasure', x: 350, y: 320, connections: ['n3', 'n6'] },
            { id: 'n6', label: 'Ao Phát Quang', type: 'mob', x: 480, y: 200, connections: ['n4', 'n5', 'n7'] },
            { id: 'n7', label: 'Cây Mẹ', type: 'boss', x: 600, y: 200, connections: ['n6'] },
        ],
    },
];
